### ISSUE TITLE
Static 3Delight.lib?

### ISSUE THREAD

**Issue by ilayshp** [FMalmberg/3Delight-for-Cinema-4D#31]
Hello
How are you resolve loading of 3Delight.DLL?
Put in root with c4d.exe or ...

I try to add preprocessor _STATIC_3DELIGHT_ or adding of this to **Bool PluginStart(void)**
```
#define MAXON_METHOD
maxon::String dllpath("C:/3Delight/bin");
MAXON_METHOD void AddDllPath(const maxon::Url & dllpath);
```
I only got working if add to root

**Comment by OgersRuda** [comment]
Hello,
For now we have resolved this issue using delayed loading of DLLs of MSVC linker. 
So you have to add 3Delight.Dll in the Linker>Input>Delay Linked Dlls of each project (3DLfC4D, 3DLfC4D geometry and others). We will try to fix this in other updates so there will be no need to do this manually.
Also you have to make sure that C:/3Delight/bin is added to your PATH environment variables.
Please let us know if this works for you.

**Comment by ilayshp** [comment]
Hello Ogers. Yes, it works! I miss one thing, in delay-dll, i set 2 paths to find out: $(DELIGHT)/bin/3Delight.dll;3Delight.dll
Why did i do before?! )))) (me, silly newbie)
Thank you!
